safe:         false
auto:         false
server:       true
server_port:  80 
baseurl:      /

source:       .
destination:  ./_site
plugins:      ./_plugins

future:       true
lsi:          false
pygments:     false
markdown:     maruku
permalink:    date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
